### ISSUE TITLE
http.password doesn't do anything

### ISSUE THREAD

**Issue by bachya** [philhawthorne/ha-dockermon#3]
My `configuration.yaml` looks like this:

```yaml
debug: false
http:
  port: 8126
  username: <USER>
  password: <PASSWORD>
docker_connection:
  type: socket
  path: /var/run/docker.sock
  host:
  port:
```

Despite giving HTTP credentials, I don't appear to need them: `http://127.0.0.1:8126/container/<container_name>` returns results without any Basic Auth in place.

Is there something special I need to do? Thanks!
