### ISSUE TITLE
Long passwords don't allow authentication

### ISSUE THREAD

**Issue by cstuder** [philhawthorne/ha-dockermon#35]
I've configured `ha-dockermon` with a 64 character password and couldn't authenticate afterwards:

```yaml
http:
  username: username
  password: Jn8NY8Uq2YkImt3peuQhC8YNX3gvf3CjRAMjZJeZH4FOK6FjsZoXNGxeBfzktSGj
```

(Just a sample password, don't worry...)

Any requests responded with a `401 Unauthorized` header, both from Home Assistant and Curl.

Workaround: Shortening the password to 28 characters in my case allows the request to go through and everything works perfectly.

Strangely I can't see any limitation of password length in the source code of `ha-dockermon`, neither any indication of it in the used library `express-basic-auth`.
