### ISSUE TITLE
Support for a secrets.yaml

### ISSUE THREAD

**Issue by bachya** [philhawthorne/ha-dockermon#6]
Would be great to have this for storage in public repositories. Thanks!

**Comment by philhawthorne** [comment]
Hmm I'm not sure if this is possible. 

Home Assistant and HA-Dockermon use YAML. The secrets.yaml implementation is unique to Home Assistant and is not natively supported by the YAML markup.

As there's only one config file for HA-Dockermon, perhaps it would be better to just not commit it publicly? Alternatively, perhaps it would be better to expose some environment flags which can be set in the `docker run` command to setup HTTP auth. Allowing you to have authentication working in HA-Dockermon, but not exposed in any YAML: files?

**Comment by bachya** [comment]
It isn't possible to do the same thing, say, AppDaemon does (i.e., if `secrets.yaml` exists in the configuration directory, use its values in place of the corresponding tokens within `configuration.yaml`)?

**Comment by philhawthorne** [comment]
Hmm not really. AppDaemon and Home Assistant use a Python library which can add some custom stuff to the YAML markup language for secrets.

HA-Dockermon uses NodeJS, and the library I am using to read YAML doesn't support constructors. 

However, HA-Dockermon _should_ import any YAML file you place inside the configuration directory. So, you could have `configuration.yaml` setup without secrets in place, just use a default value. Then put a `secrets.yaml` file there, with anything secret you want. When HA-Dockermon runs, it will merge `configuration.yaml` and `secrets.yaml` together.

**Comment by bachya** [comment]
Got it. Thank you!
 
 
 
>  
>  
>  
>    
>    
>  
>

**Comment by bachya** [comment]
Quick follow up: the suggestion above worked. For future readers, my `configuration.yaml` looks like this:

```yaml
debug: false
http:
  port: 8126
  username: USERNAME
  password: PASSWORD
docker_connection:
  type: socket
  path: /var/run/docker.sock
  host:
  port:
```

...and my `secrets.yaml` (in the same directory) looks like this:

```yaml
http:
  password: <actual password>
  username: <actual username>
```
