### ISSUE TITLE
Reporting wrong container

### ISSUE THREAD

**Issue by glassbase** [philhawthorne/ha-dockermon#7]
I was wondering why my HA switch showed mysql container as off when I knew it definitely was running. Started investigating and I found an issue. 

I have a mysql container and a mysql_backup container. Here is exert of my compose file. 

```
  mysql:
    container_name: mysql
    image: linuxserver/mysql:latest
    restart: unless-stopped
    hostname: mysql
    volumes:
      - /home/xxxxx/mysql:/config
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxx
    ports:
      - "3306:3306"

  mysql_backup:
    container_name: mysql_backup
    image: deitch/mysql-backup:latest
    restart: unless-stopped
    hostname: mysql_backup
    volumes:
      - /home/xxxxx/mysql-backup:/backups
    environment:
      - DB_USER=root
      - DB_PASS=xxxxxxx
      - DB_DUMP_BEGIN=1201
      - DB_DUMP_TARGET=/backups
      - DB_SERVER=10.0.0.8
```

Results of `http://10.0.0.8:8126/container/mysql` shows status of the backup container:
`{"state":"running","status":"Up 34 seconds","image":"deitch/mysql-backup:latest"}`
